### ISSUE TITLE
如何參與翻譯？

### ISSUE THREAD

**Issue by LImoritakeU** [pgsql-tw/twpug-doc#38]
如題：

近期開始接觸postgresql，發現這個專案，想說在閱讀的文件的過程中能順手協助翻譯，不過有點不知道如何參與呢？

**Comment by ycku** [comment]
先謝謝你可以一起協作
因為我們文件使用gitbook，設定和這個專案連動，在這裡commit，gitbook會同步編譯。
所以**你只要在這個專案裡找你想要協作的md檔，然後送PR即可**。
由於都是用markdown，所以格式上在github預覽就和最後結果相去不遠了。

一次翻一兩段也可以，不用一次一整章，
有空就隨手做。

有些章節還沒貼過來，如果你想翻譯的部份沒有，請開issue單再assign給我。
謝謝。
